### PR TITLE
use compressed pickle files

### PR DESCRIPTION
**Pull request by pepijndevos**
Untested.

Hopefully should resolve our pypi compression problems.

### CODE REVIEW

**Review by david65536 — COMMENTED** [review]
When attempting to build and program a simple counter (my first program), I get the following error which could be related to this commit affecting gowin_pack.py.  I am not familiar with the library but it is possible that [importlib.resources.files needs migration](https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy)    

```Traceback (most recent call last):
  File "/Users/me/Documents/LushayFPGA/oss-cad-suite/libexec/gowin_pack", line 33, in <module>
    sys.exit(load_entry_point('Apycula==0.8.2a2.dev1+g8e31050', 'console_scripts', 'gowin_pack')())
  File "/Users/me/Documents/LushayFPGA/oss-cad-suite/lib/python3.8/site-packages/Apycula-0.8.2a2.dev1+g8e31050-py3.8.egg/apycula/gowin_pack.py", line 984, in main
AttributeError: module 'importlib.resources' has no attribute 'files'
Finished Bitstream Generation
Task finished with errors exiting
Toolchain Completed
```

I am on an M2 Mac Mini and VS Code.  I added the Lushay Extension and also set up oss-cad-suite-darwin-arm64-20230714.tgz.  It allows me to `Build and Program` using the FPGA Toolchain but exits with the above error.

**Comment by yrabbit** [comment]
> module 'importlib.resources' has no attribute 'files'
What's your version of Python?

Here it uses the files API, which should work on Python versions >=3.9. At least for me it works on 3.9.

**Comment by david65536** [comment]
I thought I had VSCode set up to use either `usr/bin/python3` which is `3.9.6`, or `usr/local/bin/python3` which is `3.11.4`.  I downloaded `[oss-cad-suite-darwin-arm64-20230714.tgz](https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-07-14/oss-cad-suite-darwin-arm64-20230714.tgz) from the [releases directory ](https://github.com/YosysHQ/oss-cad-suite-build/releases) which is latest and built today.  

It looks like maybe the toolchain is using the above release's `oss-cad-suite/lib/python3.8/`  which contains `oss-cad-suite/lib/python3.8/site-packages/Apycula-0.8.2a2.dev1+g8e31050-py3.8.egg/apycula/gowin_pack.py`.  

I unzipped the Apycula-0.8.2a2.dev1+g8e31050-py3.8.egg file and confirmed that the `gowin_pack.py` inside has the change in line 984 from `32f21948799cf55f09af2e6abf48df38c91f9360` (this PR):
```
with gzip.open(importlib.resources.files("apycula").joinpath(f"{device}.pickle"), 'rb') as f:
        db = pickle.load(f) 
```

I will try to see if I can get my environment to use something >= Python 3.9, but in the meantime could it be that something newer than python3.8 should be packaged in the YosysHQ/oss-cad-suite-build/releases?  Thanks for your help and will try to use Python 3.9 next.

**Comment by david65536** [comment]
I ended up using a previous release (oss-cad-suite-darwin-arm64-20230615.tgz) which is working for now.

**Comment by pepijndevos** [comment]
Oh darn. We claim to support Python 3.6 so this breakage wasn't intentional.
Conceptually I think supporting whatever reasonably stable Linux distros are currently shipping is good practice.
It looks like most have been on 3.9 or higher for a good while now: https://distrowatch.com/dwres.php?resource=package-in-distro&pkg=Python

I would gladly accept a PR that restores backwards compatibility either way.

I'll also ping @mmicko to see how they feel about Python versioning in oss-cad-suite.

**Comment by david65536** [comment]
Sounds good!  I will wait to hear what @mmicko thinks.

**Comment by mmicko** [comment]
@pepijndevos @david65536 right now we are distributing 3.8, moving to 3.9 would require change in complete infrastructure (since base cross compile image is using 3.8) and also making a big patch for mingw build to move to 3.9. We will move forward eventually but not now :( 
If possible please create a patch making it backward  compatible with at least 3.8. Thanks

**Comment by pepijndevos** [comment]
So `open_binary` is what we can use in pre-3.11 when it became deprecated, and `files` is what we can use post-3.9.

I think something like `gzip.GzipFile(fileobj=importlib.resources.open_binary("apycula", f"{args.device}.pickle"))` might do the trick, modulo context manager stuff.

Not sure if we should add a version check, or just use the deprecated method until it's actually gone, I'm fine either way.

@david65536 do you want to make a PR, or should I clear some time to fix this?

**Comment by david65536** [comment]
Sure I can take a look and make a PR!

**Comment by david65536** [comment]
Sorry for the delay on this - I have a putative fix but was having trouble testing due to the Apycula==0.8.2a2.dev1+g8e31050 library being packaged into an egg.  The workaround seemed to be a bit involved (editing the easyinstall entry scripts and a resulting few further steps which I got blocked on) -  it seems easiest to push a PR then download and test a build for `oss-cad-suite` derived from that PR.  Is that something that can currently happen via CI?

I am having some issues pushing the PR but could be due to my familiarity with git. Currently I get `remote: Permission to YosysHQ/apicula.git denied to david65536.` when I try to run `git push`.

```
git remote -v
origin	https://github.com/YosysHQ/apicula.git (fetch)
origin	https://github.com/YosysHQ/apicula.git (push)
```

**Comment by pepijndevos** [comment]
What you'll want to do is in the top right here click fork, which will make
a repo under your account. Git clone that fork.

You can indeed push to that fork, create a PR from that, and download the
egg from artifacts.

You can also copy the pickle files into apycula folder and run `pip install
-e .` which makes an editable installation from the current folder. I would
recommend doing that in a virtualenv.

```
git clone yourfork
cd apicula
viertualenv env
source env/bin/activate
# copy pickle files into apycula
pip install -e .
git checkout -b py38
git commit -am "support python 3.8"
git push
```

**Comment by david65536** [comment]
Thanks @pepijndevos !  I made a PR [here](https://github.com/YosysHQ/apicula/pull/189) and was able to test in the context of the oss-cad-suite release using an egg I created. Being pretty new to all of this how do I refer to `GW1N-1.pickle, GW1N-9.pickle, GW1NS-2.pickle, GW1NZ-1.pickle, GW1N-4.pickle, GW1N-9C.pickle, GW1NS-4.pickle, GW2A-18.pickle` if I don't want to call them "the pickle files"?

**Comment by pepijndevos** [comment]
We usually call them chip DBs
